### ISSUE TITLE
problem with japanese language

### ISSUE THREAD

**Issue by kp-phongpt** [yii2tech/csv-grid#21]
How can i export csv using Japanese lang? I'm tryin to export csv using Japanese lang and here is my result 
![image](https://user-images.githubusercontent.com/41980348/44295133-2eaec080-a2cd-11e8-8e46-74128a68080a.png)

**Comment by klimov-paul** [comment]
That is I can not say, since I do not use Japanese anywhere.
Note that CSV is a simple text file and text you provide is written inside it as it is.
In case you have invalid text inside *.csv file, check char encoding. If you have problem with particular program like Excel or OpenOffice while viewing results, search for the solution regardless to these applications.
